CONSOLE_NONE=0;CONSOLE_ERROR=1;CONSOLE_WARN=2;CONSOLE_INFO=3;CONSOLE_DEBUG=4;CONSOLE_LOG=5;CONSOLE_ALL=9;var R=function(a){for(var b=CONSOLE_NONE,d=a.console,e=/(iphone|ipad|ipod|android)/.test(navigator.userAgent.toLowerCase()),
c={},n=[],j,h,o=["error","warn","info","debug","log"],q="assert clear count dir dirxml exception group groupCollapsed groupEnd profile profileEnd table time timeEnd trace".split(" "),p=q.length;--p>=0;)(function(g){c[g]=function(){b!==0&&d&&d[g]&&d[g].apply(d,arguments)}})(q[p]);for(p=o.length;--p>=0;)(function(g,r){c[r]=function(){n.push([r].concat(Array.prototype.slice.call(arguments)));if(j&&(h||!d||!d.log))j.apply(a,arguments);if((b>0?b>g:o.length+b<=g)&&d)try{d[r]?e?d[r].call(d,arguments.join(" ")):
d[r].apply(d,arguments):e?d.log.call(d,arguments.join(" ")):d.log.apply(d,arguments)}catch(D){d.log(Array.prototype.slice.call(arguments).join(" "))}}})(p,o[p]);c.getLogs=function(){return n};c.setCallback=function(g,r){j=g;h=!!r};c.setLevel=function(g){b=Number(g)};return c}(window);window.debug=R;(function(a){function b(Y,T){var O=/^\w+\:\/\//,ga;if(typeof Y!=c)Y="";if(typeof T!=c)T="";ga=(O.test(Y)?"":T)+Y;return(O.test(ga)?"":ga.charAt(0)==="/"?ca:W)+ga}function d(Y,T){function O(f,S){if(f[o]&&f[o]!==D&&f[o]!=="loaded"||S[t])return u;f[B]=f[l]=s;return w}function ga(f,S,V){if((V=!!V)||
O(f,S)){S[t]=w;for(var P in za)if(za[z](P)&&!za[P][t])return;Ab=w;Ba()}}function oa(f){if(ba.call(f[p])===m){f[p]();f[p]=s}}function ea(f,S){if(O(f,S)){S[q]=w;X(function(){F[S[A]].removeChild(f);oa(S)},0)}}function U(f,S){if(f[o]===4){f[l]=k;S[q]=w;X(function(){oa(S)},0)}}function Nb(f,S,V,P,G,da){var Ia=f[A];X(function(){if("item"in F[Ia]){if(!F[Ia][0]){X(arguments.callee,25);return}F[Ia]=F[Ia][0]}var Ca=N.createElement(h);if(typeof V==c)Ca.type=V;if(typeof P==c)Ca.charset=P;if(ba.call(G)===m){Ca[B]=
Ca[l]=function(){G(Ca,f)};Ca.src=S;if(aa)Ca.async=u}F[Ia].insertBefore(Ca,Ia===n?F[Ia].firstChild:s);if(typeof da==c){Ca.text=da;ga(Ca,f,w)}},0)}function Bb(f,S,V,P){I[f[g]]=w;Nb(f,S,V,P,ga)}function sa(f,S,V,P){var G=arguments;if(Da&&f[q]==s){f[q]=u;Nb(f,S,i,P,ea)}else if(!Da&&f[q]!=s&&!f[q])f[p]=function(){sa.apply(s,G)};else Da||Bb.apply(s,G)}function pa(f,S,V,P){var G=arguments,da;if(Da&&f[q]==s){f[q]=u;da=f.xhr=fa?new fa("Microsoft.XMLHTTP"):new a.XMLHttpRequest;da[l]=function(){U(da,f)};da.open("GET",
S);da.send("")}else if(!Da&&f[q]!=s&&!f[q])f[p]=function(){pa.apply(s,G)};else if(!Da){I[f[g]]=w;Nb(f,S,V,P,s,f.xhr.responseText);f.xhr=s}}function ta(f){if(f.allowDup==s)f.allowDup=T.dupe;var S=f.type,V=f.charset,P=f.allowDup;f=b(f.src,Ob);var G=b(f).indexOf(ca)===0;if(typeof V!=c)V=s;P=!!P;if(P=!P){if(!(P=I[f]!=s)){if(!(P=Da&&za[f]))a:{for(var da=-1;P=H[++da];)if(typeof P.src==c&&f===b(P.src)&&P.type!==i){P=w;break a}P=u}P=P}P=P}if(P)za[f]!=s&&za[f][q]&&!za[f][t]&&G&&ga(s,za[f],w);else{if(za[f]==
s)za[f]={};P=za[f];if(P[A]==s)P[A]=Pb;P[t]=u;P[g]=f;na=w;if(!ub&&Qb&&G)pa(P,f,S,V);else!ub&&dc?sa(P,f,S,V):Bb(P,f,S,V)}}function Xa(f){Y&&!ub&&Cb.push(f);if(!Y||Ja)f()}function Rb(f){var S=[],V;for(V=-1;++V<f.length;)if(ba.call(f[V])===v)S=S.concat(Rb(f[V]));else S[S.length]=f[V];return S}Y=!!Y;if(T==s)T=K;var Ab=u,Ja=Y&&T[r],dc=Ja&&T.cache,ub=Ja&&T.order,Qb=Ja&&T.xhr,uc=T[E],Pb=T.which,Ob=T.base,Ba=k,na=u,Db,Da=w,za={},Cb=[],va=s;Ja=dc||Qb||ub;Db={script:function(){y(va);var f=Rb(arguments),S=Db,
V;if(uc)for(V=-1;++V<f.length;){if(V===0)Xa(function(){ta(typeof f[0]==c?{src:f[0]}:f[0])});else S=S.script(f[V]);S=S.wait()}else Xa(function(){for(V=-1;++V<f.length;)ta(typeof f[V]==c?{src:f[V]}:f[V])});va=X(function(){Da=u},5);return S},wait:function(f){y(va);Da=u;ba.call(f)===m||(f=k);var S=d(w,T),V=S.trigger,P=function(){try{f()}catch(da){}V()};delete S.trigger;var G=function(){if(na&&!Ab)Ba=P;else P()};Y&&!na?Cb.push(G):Xa(G);return S}};if(Y)Db.trigger=function(){for(var f,S=-1;f=Cb[++S];)f();
Cb=[]};return Db}function e(Y){var T,O={},ga={UseCachePreload:"cache",UseLocalXHR:"xhr",UsePreloading:r,AlwaysPreserveOrder:E,AllowDuplicates:"dupe"},oa={AppendTo:A,BasePath:"base"};for(T in ga)oa[T]=ga[T];O.order=!!K.order;for(T in oa)if(oa[z](T)&&K[oa[T]]!=s)O[oa[T]]=Y[T]!=s?Y[T]:K[oa[T]];for(T in ga)if(ga[z](T))O[ga[T]]=!!O[ga[T]];if(!O[r])O.cache=O.order=O.xhr=u;O.which=O.which===n||O.which===j?O.which:n;return O}var c="string",n="head",j="body",h="script",o="readyState",q="preloaddone",p="loadtrigger",
g="srcuri",r="preload",D="complete",t="done",A="which",E="preserve",l="onreadystatechange",B="onload",z="hasOwnProperty",i="script/cache",m="[object Function]",v="[object Array]",s=null,w=true,u=false,N=a.document,fa=a.ActiveXObject,X=a.setTimeout,y=a.clearTimeout,ba=Object.prototype.toString,k=function(){},F={},I={},W=/^[^?#]*\//.exec(a.location.href)[0],ca=/^\w+\:\/\/\/?[^\/]+/.exec(W)[0],H=N.getElementsByTagName(h),Q=a.opera&&ba.call(a.opera)=="[object Opera]",J="MozAppearance"in N.documentElement.style,
aa=N.createElement(h).async===true,K={cache:!(J||Q),order:J||Q||aa,xhr:w,dupe:w,base:"",which:n};K[E]=u;K[r]=w;F[n]=N.head||N.getElementsByTagName(n);F[j]=N.getElementsByTagName(j);a.$LAB={setGlobalDefaults:function(Y){K=e(Y)},setOptions:function(Y){return d(u,e(Y))},script:function(){return d().script.apply(s,arguments)},wait:function(){return d().wait.apply(s,arguments)}};(function(Y,T,O){if(N[o]==s&&N[Y]){N[o]="loading";N[Y](T,O=function(){N.removeEventListener(T,O,u);N[o]=D},u)}})("addEventListener",
"DOMContentLoaded")})(window);(function(){var a=false,b=/xyz/.test(function(){})?/\b_super\b/:/.*/;this.MingClass=function(){};MingClass.extend=function(d){function e(){!a&&this.init&&this.init.apply(this,arguments)}var c=this.prototype;a=true;var n=new this;a=false;for(var j in d)n[j]=typeof d[j]=="function"&&
typeof c[j]=="function"&&b.test(d[j])?function(h,o){return function(){var q=this._super;this._super=c[h];var p=o.apply(this,arguments);this._super=q;return p}}(j,d[j]):d[j];e.prototype=n;e.constructor=e;e.extend=arguments.callee;return e}})();XHR=function(){function a(d){try{return JSON.parse(d)}catch(e){return d}}
function b(d,e,c,n,j,h){var o=/^(\w+:)?\/\/([^\/?#]+)/.exec(e);o=o&&(o[1]&&o[1].toLowerCase()!==location.protocol||o[2].toLowerCase()!==location.host);var q=window.XDomainRequest&&o?new XDomainRequest:window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");if(h==="script"&&d==="GET"&&o){var p=document.getElementsByTagName("head")[0]||document.documentElement,g=document.createElement("script"),r=false;g.src=e;g.onload=g.onreadystatechange=function(){if(!r&&(!this.readyState||
this.readyState==="loaded"||this.readyState==="complete")){r=true;g.onload=g.onreadystatechange=null;p&&g.parentNode&&p.removeChild(g)}};p.insertBefore(g,p.firstChild);return true}q.open(d,e,!!n);if(q.setRequestHeader){q.setRequestHeader("Content-Type","application/x-www-form-urlencoded");o||q.setRequestHeader("X-Requested-With","XMLHttpRequest")}if(j)q.withCredentials=true;if(n)q.onreadystatechange=function(){q.readyState===4&&n.call(q,a(q.responseText),q.status)};q.send(c);return n?true:a(q.responseText)}
this.get=function(d,e){return b("GET",d,null,e)};this.getWithCredentials=function(d,e){return b("GET",d,null,e,true)};this.getJson=function(d,e){return b("GET",d,null,null,e,"script")};this.post=function(d,e,c){return b("POST",d,e,c)};this.postWithCredentials=function(d,e,c){return b("POST",d,e,c,true)};this.request=b};window.XHR=XHR;ICanHas=function(a,
b){return{cors:function(){var d=b.XDomainRequest||b.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest;if(d){d=new Boolean(d);d.withCredentials=!window.XDomainRequest}return d}(),orientation:window.orientation!==void 0,touch:"ontouchstart"in b,video:function(){var d=a.createElement("video"),e=!!d.canPlayType;if(e){e=new Boolean(e);e.vp6=d.canPlayType('video/x-flv; codecs="vp6"')||false;e.vp8=d.canPlayType('video/webm; codecs="vp8,vorbis"')||false;e.h264=navigator.userAgent.toLowerCase().search("android")>
-1?"probably":d.canPlayType('video/mp4; codecs="avc1.42E01E"')||d.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"')||false}return e}()}}(document,window);FlashDetect=function(){var a=navigator,b=false,d=0,e=0,c=0,n=null,j=null;if(a.plugins&&a.plugins.length){if((a=a.plugins["Shockwave Flash"])&&a.description){n=
a.description;b=true}}else if(a.mimeTypes&&a.mimeTypes.length){if((a=a.mimeTypes["application/x-shockwave-flash"])&&a.enabledPlugin)b=true}else try{n=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version");b=true}catch(h){}if(n){j=n.replace(/\D+/g,".").replace(/^\./,"");a=j.split(".");d=parseInt(a[0],10);e=parseInt(a[1],10);c=parseInt(a[2],10)}return{installed:b,raw:n,version:j,major:d,minor:e,revision:c,versionAtLeast:function(o,q,p){o=o||10;q=q||0;p=p||0;var g=[d,e,c],r=arguments,
D=Math.min(g.length,r.length),t;for(t=0;t<D;t++)if(g[t]>=r[t]){if(!(t+1<D&&g[t]===r[t]))return true}else return false}}}();$m={};(function(a){function b(i,m,v){if(a.type(v)!=="array"||v===o)v=[v];for(var s=0,w=v.length;s<w;s++)v[s][i]||(v[s][i]=m);a[i]=function(){var u=
Array.prototype.slice.call(arguments),N=u.shift();return m.apply(N,u)}}function d(i,m,v,s){v[i]=m;s.push(i);s.length>1E3&&delete v[s.shift()];return m}function e(i,m){if(i in m)return m[i];return false}function c(){var i=this.valueOf();return i<0?~~i-1:~~i}function n(i,m){return this<m?i>this?i:this:m}function j(i,m){var v=this.valueOf()+"";return Array(i-v.length+1).join(m||"0")+v}if(!window.Element)window.Element={};for(var h=document,o=Array.prototype,q=!window.HTMLElement?{}:HTMLElement.prototype,
p=!window.NodeList?{}:NodeList.prototype,g=Number.prototype,r=String.prototype,D=window,t={},A=[],E="Boolean Number String Function Array Date RegExp Object".split(" "),l=[],B=0,z=E.length;B<z;B++)l["[object "+E[B]+"]"]=E[B].toLowerCase();a.type=function(i){return i==null?String(i):l[Object.prototype.toString.call(i)]||"object"};a.isArray=function(i){return a.type(i)==="array"};a.emptyFunction=function(){};a.clone=function(i){var m=a.isArray(i)?[]:{};for(B in i)if(B!=="clone")m[B]=i[B]&&a.type(i[B])===
"object"?a.clone(i[B]):i[B];return m};a.addEventListener=function(i,m,v){window.addEventListener?i.addEventListener(m,v,false):i.attachEvent("on"+m,v)};a.removeEventListener=function(i,m,v){window.removeEventListener?i.removeEventListener(m,v,false):i.detachEvent("on"+m,v)};a.findKey=function(i,m){for(var v in m)if(m.hasOwnProperty(v)&&m[v]===i)return v;return false};a.fibonacci=function(i){var m=Math.sqrt(5);return(1/m*Math.pow((1+m)/2,i)-1/m*Math.pow((1-m)/2,i)).round()};a.withinElement=function(i,
m){var v=m.relatedTarget;try{if(v&&v!==document&&!v.parentNode)return true;for(;v&&v!==i;)v=v.parentNode;if(v!==i)return false}catch(s){}return true};b("abs",function(){var i=this.valueOf();return i<0?-i:i},g);b("addClass",function(i){if(this.length&&this.forEach)this.forEach(function(m){a.addClass(m,i)});else if(!a.hasClass(this,i))this.className=this.className.split(" ").concat(i).unique().join(" ").trim();return this},[q,p]);b("attr",function(i,m){if(a.type(i)==="object"){for(prop in i)i[prop]===
null||i[prop]===""?this.removeAttribute(prop):this.setAttribute(prop,i[prop]);return this}if(m===void 0)return this.getAttribute(i);m===null||m===""?this.removeAttribute(i):this.setAttribute(i,m);return this},q);b("ceil",function(){return c.call(this.valueOf()+1)},g);b("clamp",function(i,m,v){function s(){if(checkCount>200)return false;if(w.innerText!=i||w[property]==0){checkCount++;setTimeout(s,1)}else a:if(!(w[property]<=v)){for(;w[property]>v;){w.innerText=w.innerText.substr(0,w.innerText.length-
1);if(w.innerText==""||w.innerText.length==0)break a}w.innerText=w.innerText.substr(0,w.innerText.length-3)+"..."}}var w=this;w.innerHTML=i;property=m=="height"?"clientHeight":"clientWidth";checkCount=0;s();return w},q);b("clear",function(){this.childNodes.forEach(function(i){i.remove&&i.remove()});return this},q);b("computeStyle",function(i){if(!D.getComputedStyle)D.getComputedStyle=function(m){this.el=m;this.getPropertyValue=function(v){var s=/(\-([a-z]){1})/g;if(v=="float")v="styleFloat";if(s.test(v))v=
v.replace(s,function(w,u,N){return N.toUpperCase()});return m.currentStyle&&m.currentStyle[v]?m.currentStyle[v]:null};return this};return D.getComputedStyle(this,null).getPropertyValue(i)},q);b("contains",function(i){return this.indexOf(i)!==-1},[o,r]);b("css",function(i,m){if(a.type(i)==="object"){for(prop in i)this.style[prop]=i[prop];return this}if(m===void 0)return this.style[i];this.style[i]=m===null||m===""?"":m;return this},q);b("floor",c,g);b("forEach",function(i,m){if(a.type(i)==="function")for(var v=
this.length>>>0,s=0;s<v;s++)s in this&&i.call(m,this[s],s,this)},[o,p]);b("getElementsByClassName",function(i){var m=[],v=0,s,w,u;if(document.evaluate){s=".//*[contains(concat(' ', @class, ' '), ' "+i+" ')]";for(w=document.evaluate(s,this,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);u=w.snapshotItem(v++);)m[m.length]=u}else{s=RegExp("(^|\\s)"+i+"(\\s|$)");w=this.getElementsByTagName("*");v=0;for(var N=w.length;v<N;v++){u=w[v];if(u.className===i||s.test(u.className))m[m.length]=u}}return m},h);
b("hasAncestor",function(i){if(i===this)return true;for(var m=this.parentNode;m;){if(m===i)return true;m=m.parentNode}return false},q);b("hasClass",function(i){if(i.splice){for(var m=this.className.split(" "),v=0,s=m.length;v<s;v++)if(i.contains(m[v]))return true;return false}return RegExp("(?:^|\\s+)"+i+"(?:\\s+|$)").test(this.className)},q);b("hex2rgb",function(){if(cached=e(this,t))return cached;var i=parseInt(this.replace("#",""),16);i=[(i&16711680)>>16,(i&65280)>>8,i&255];return d(this,"rgb("+
i.join(",")+")",t,A)},r);b("html",function(i){if(i===void 0)return this.innerHTML;this.innerHTML=i;return this},q);b("indexOf",function(i){for(var m=0,v=this.length;m<v;m++)if(this[m]==i)return m;return-1},o);b("innerHeight",function(){for(var i=0,m,v=0,s=this.childNodes.length;v<s;v++){m=this.childNodes[v];if(m.style)i+=m.clientHeight+(a.toInt(a.computeStyle(m,"margin-top"),10)||0)+(a.toInt(a.computeStyle(m,"margin-bottom",10))||0)}return i},q);b("limit",n,g);b("map",function(i,m){for(var v=this.length>>>
0,s=Array(v),w=0;w<v;w++)if(w in this)s[w]=i.call(m,this[w],w,this);return s},o);b("max",function(){return Math.max.apply(Math,this)},o);b("min",function(){return Math.min.apply(Math,this)},o);b("pad",j,[r,g]);b("position",function(){var i=0,m=0,v=this;if(v.offsetParent){do{i+=v.offsetLeft;m+=v.offsetTop}while(v=v.offsetParent)}return{x:i,y:m}},q);b("prependChild",function(i){return this.insertBefore(i,this.firstChild)},q);b("q",function(i){return this.querySelector(i)},[h,q]);b("qa",function(i){return this.querySelectorAll(i)},
[h,q]);b("remove",function(){if(this.length)this.forEach(function(i){i.parentNode&&i.parentNode.removeChild(i)});else this.parentNode&&this.parentNode.removeChild(this)},[q,p]);b("removeClass",function(i){if(this.length&&this.forEach)this.forEach(function(m){a.removeClass(m,i)});else if(a.hasClass(this,i))this.className=this.className.replace(RegExp("(?:^|\\s+)"+i+"(?:\\s+|$)","g")," ").trim();return this},[q,p]);b("rgb2hex",function(){if(cached=e(this,t))return cached;var i=this.match(/\d{1,3}/g).slice(0,
3);i=i.map(function(m){return j.call(n.call(parseInt(m,10),0,255).toString(16),2)});return d(this,i.join(""),t,A)},r);b("round",function(){return c.call(this.valueOf()+0.5)},g);b("toInt",function(i){return parseInt(this.valueOf?this.valueOf():this,i||10)},[r,g]);b("toFloat",function(i){return parseFloat(this.valueOf(),i||10)},[r,g]);b("trim",function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},r);b("ucfirst",function(){return this.charAt(0).toUpperCase()+this.slice(1)},r);b("unique",
function(){var i=[],m=0,v=this.length;a:for(;m<v;m++){for(var s=0,w=i.length;s<w;s++)if(i[s]===this[m])continue a;i[i.length]=this[m]}return i},o);b("wrap",function(i,m){var v=this,s=a.addClass(document.createElement(i),m||"");v.length||(v=Array(this));v.forEach(function(w,u){u===0&&w.parentNode.replaceChild(s,w);s.appendChild(w)});return s},[q,p])})($m);EventManager=function(){function a(e){if(!b[e]){var c=document.createElement("a");c.id="Event:"+e;d.appendChild(c);b[e]=
c}return b[e]}var b={},d=document.createElement("div");d.id="events"+(new Date).getTime();document.body.appendChild(d);this.bind=function(e,c){var n=a(e);window.addEventListener?n.addEventListener("click",c,false):n.attachEvent("onclick",c);return this};this.unbind=function(e,c){var n=a(e);window.removeEventListener?n.removeEventListener("click",c,false):n.detachEvent("onclick",c);return this};this.fire=function(e,c){var n,j=a(e);if(document.createEvent){n=document.createEvent("HTMLEvents");n.initEvent("click",
false,true);n.name=e;n.data=c;return j.dispatchEvent(n)}else{try{c=JSON.stringify(c)}catch(h){}n=document.createEventObject();n.name=e;n.data=c;return j.fireEvent("onclick",n)}}};window.EventManager=EventManager;var vb=
"ming",wb="moogaloop",kc="noplayer",Ac="nomobile",db="mobile",jc="touch",Mb="desktop",Nc="html",Mc="flash",ja="noplayer",ya="hd",Ta="sd",Pa="mobile",Pc=[ya,Ta,Pa],ld="pl_volume",Jc="hd_preference",md="scaling_preference",Hb="onwebkittransitionend"in window?"webkitTransitionEnd":"transitionEnd",Gb=8,nd=250,Kc=140,Lc=200,od=265;ja=200;var Ub=7,mc=1.5,Qc=2E3,Oc=1500,Ma=1,Qa=2,Kb=3,ka=4,ra=5,La=6,$b=7,yb=8,gb=9,xc=10,zc=11,wc=12,yc=13,nc=14,bc=15,mb=16,Rc=17,qc=18,rc=19,cc=20,Sc=21,sc=22,tc=23,ia=24,
wa=25,fb=26,Za=27,Zb=28,ma=29,Lb=30,Tc=31,Ea=32,nb=33,ob=34,Ra=35,vc=36,jb="loadProgress",kb="playProgress",ib="play",hb="pause",xb="finish",lb="seek",tb="ready",jd="error",lc="addEventListener()",Bc="removeEventListener()",qb="play()",pb="pause()",rb="seekTo()",sb="unload()",Ua="setColor()",bb="setLoop()",cb="setVolume()",Ga="getDuration()",Fa="getCurrentTime()",Va="getVolume()",Cc="getColor()",zb="getLoop()",Dc="getVideoUrl()",Ec="getVideoEmbedCode()",$a="getVideoWidth()",ab="getVideoHeight()",
Na="paused()",Ka="a",pd="az",ac="z",qd="by",Sb="ao",hc="aq",M="bl",Z="ah",pc="bf",Yb="ab",fd="i",gd="m",hd="n",id="o";ja="ae";ja="g";ja="c";ja="g";var Uc="aw",rd="n";ja="ak";ja="ck";var Eb="w",Fb="v",Ib="y",Ya="p",Oa="k",Tb="u",Sa="j",gc="bi",ic="bb",ad="co",bd="x",fc="ca",cd="ar",dd="be",eb="bz",ec="cx",sd="ax",xa="b",Fc="h",Gc="am";ja="cb";var Vc="i",td="bn",ud="ay",Vb="aj";ja="cy";var vd="ac",wd="m";ja="as";Ya="p";var xd="al",yd="ai",Ha="e",ua="d",Wb="af",Xb="ci",oc="bt",Wc="bj",zd="o",Ad="videos",
Bd="at",Ic="bc",Wa="r",Cd="bm",Xc="bk",la="l",Hc="q",Dd="bp",Yc="ag",Ed="cc",Zc="bv";ja="k";var ed="bs",kd="cf";if(window.$){$=$;$$=$$}var x=MingClass.extend({init:function(a,b,d){function e(){if(!ICanHas.video)return false;if(o.ie)return false;if(o.safari&&o.safari<4)return false;for(var q in c.config.video.files)if(ICanHas.video[q])return true;return false}var c=this,n=b.assets,j,h;j=navigator;
h=j.userAgent.toLowerCase();j=j.platform.toLowerCase();var o={webkit:"webkitAppearance"in document.documentElement.style?parseFloat(h.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false,firefox:/firefox/.test(h)?h.replace(/^.*firefox\/(\d+\.\d+\.\d+).*$/,"$1"):false,safari:/safari/.test(h)?parseFloat(h.replace(/^.*version\/(\d+)\.(\d+)?.*$/,"$1.$2")):false,ie:navigator.appName=="Microsoft Internet Explorer",opera:window.opera&&{}.toString.call(window.opera)=="[object Opera]"||false,win:j?/win/.test(j):
/win/.test(h),mac:/mac/.test(j||h)?parseFloat(h.replace(/^.* ((\d+)(_|\.)?(\d+)?).*$/,"$2.$4")):false,linux:j?/linux/.test(j):/linux/.test(h),android:/android/.test(h)?parseFloat(h.replace(/^.* android (\d+)\.(\d+).*$/,"$1.$2")):false,playBook:/playbook/.test(h)};c.element=a;c.config=b.config;c.playerType=null;c.playerMode=null;c.playableFiles=null;c.thumbs=b.thumbs;c.api=false;c.ua=o;c.uniqueId=b.uniqueId;x.cookieDomain=c.config.request.cookie_domain;c.playerMode=function(){if(c.playerMode)return c.playerMode;
var q=Mb;if(Math.min(screen.width,screen.height)<=480||x.getCookie("test_mobiloop")=="1"||o.android&&o.android<3)q=db;else if(ICanHas.orientation)q=jc;return q}();c.playableFiles=function(){var q=c.config.video,p=q.files,g={hd:false,sd:false,mobile:false};for(codec in p)if(ICanHas.video[codec]){if(c.playerMode===db){if($m.contains(p[codec],Pa))g.mobile=codec;else if(x.mobileCanPlaySD()&&$m.contains(p[codec],Ta))g.sd=codec;break}for(var r=0,D=p[codec].length;r<D;r++){var t=p[codec][r];if(t===ya&&!g.hd)g.hd=
codec;else if(t===Ta&&!g.sd)g.sd=codec;else if(t===Pa&&!g.mobile)g.mobile=codec}}if(!c.config.security.hd_embed)g.hd=false;if(c.playerMode===jc)if(q.height*q.width>921600){R.info("Can't play HD version on iPad: too big");g.hd=false;c.config.video.hd=false}return g}();c.playerType=function(q){var p=kc;switch(q){case Mc:p=FlashDetect.installed&&FlashDetect.major>=10?wb:e()?vb:p;break;case Nc:p=c.playerMode!==db&&!c.playableFiles.hd&&!c.playableFiles.sd?FlashDetect.installed&&FlashDetect.major>=10?wb:
c.playableFiles.mobile?vb:p:e()?vb:FlashDetect.installed&&FlashDetect.major>=10?wb:p;break}if(c.playerMode===db&&!c.playableFiles.mobile){a:{q=c.config.video.files;for(codec in q)if($m.contains(q[codec],Pa)){q=true;break a}q=false}p=q?kc:x.mobileCanPlaySD()&&c.playableFiles.sd?vb:Ac}return p}(c.config.user.preferences.html===1?Nc:Mc);h=c.playerType===wb?n.moogaloop:n.ming[c.playerMode].js;j=c.playerType===wb?[]:n.ming[c.playerMode].css;R.info("Player Type:",c.playerType);R.info("Player Mode:",c.playerMode,
Math.min(screen.width,screen.height));R.info("Screen Size:",screen.width,"x",screen.height);R.info("Can play:",ICanHas.video.h264?"h264":"");R.info("Playable Files:",c.playableFiles.hd?"hd":"",c.playableFiles.sd?"sd":"",c.playableFiles.mobile?"mobile":"");c.setThumb();$m.forEach(j,function(q){var p=document.createElement("link");$m.attr(p,{rel:"stylesheet",href:n.css_path+q+(!n.cache?(q.indexOf("?")>-1?"&":"?")+(new Date).getTime():"")});document.getElementsByTagName("head")[0].appendChild(p)});j=
$LAB.setOptions({AlwaysPreserveOrder:true,BasePath:n.js_path});n.cache||(h=$m.map(h,function(q){return q+(q.indexOf("?")>-1?"&":"?")+(new Date).getTime()}));j.script(h).wait(function(){c.api=new x.API(c.config);playerElement=a.getElementsByTagName("div")[0];$m.addClass(playerElement,c.playerType===wb?ed:Ka);c.player=new (c.playerType===wb?x.Moogaloop:c.playerType===kc||c.playerType===Ac?x.NoPlayer:x.Ming)(playerElement,b.options[c.playerType===Ac?kc:c.playerType],c);d&&d.call(c)});R.info("Reticulating splines...")},
getConfig:function(){return this.config},setConfig:function(a){this.config=a},setThumb:function(){var a=this.element.getElementsByTagName("div")[0].getElementsByTagName("div")[0].getElementsByTagName("div")[0],b=a.getAttribute("data-thumb"),d=this.thumbs[640],e=this.element.clientWidth;if(e>=900)d=this.thumbs[960];if(e>=1E3)d=this.thumbs[1280];this.config.video.thumbnail=d;if(b!==d&&this.playerType===vb){if(this.config.embed.autoplay===0||this.playerMode!==Mb)a.style.backgroundImage="url("+d+")";
a.setAttribute("data-thumb",d)}}});x.setCookie=function(a,b,d,e){var c=document.getElementById(fd),n="";d=d||87600;e=e||x.cookieDomain;if(c){document.getElementById(gd).value=a;document.getElementById(hd).value=b;document.getElementById(id).value=d;window.addEventListener("message",function(j){j.data=="refresh"&&x.xhrRefresh()},false);c.submit()}else{if(d){c=new Date;c.setTime(c.getTime()+d*60*60*1E3);n="; expires="+c.toGMTString()}e="; domain="+e;document.cookie=a+"="+b+n+"; path=/"+e}};x.getCookie=
function(a){var b=document.cookie;a=a+"=";var d;if(b&&b!==""){b=document.cookie.split(";");for(var e=0,c=b.length;e<c;e++){d=b[e].trim();if(d.indexOf(a)===0)return unescape(d.substr(a.length))}}return null};x.eatCookie=function(a){document.cookie=a+"=; expires=Thu, 01-Jan-70 00:00:01 GMT;"};x.xhrRefresh=function(){var a;(new XHR).get(document.location.href,function(b){a=document.getElementsByTagName("body")[0];a.innerHTML=b;$m.forEach(a.getElementsByTagName("script"),function(d){d.innerHTML&&(new Function(d.innerHTML)).call(window)})})};
x.checkRatio=function(a,b,d){if(!b)return false;d=d.video.width/d.video.height;var e=a.clientWidth/a.clientHeight;if(Math.abs(d-e)<0.02){$m.removeClass(a,Eb);$m.removeClass(a,Fb)}else if(e>d){$m.removeClass(a,Fb);$m.addClass(a,Eb)}else{$m.removeClass(a,Eb);$m.addClass(a,Fb)}$m.removeClass(b,M)};x.mobileCanPlaySD=function(){return window.devicePixelRatio>=2};if(!x.init)x.init={queue:[],loaderAdded:false,loader:function(){x.init.queue.length>0&&x.init.queue.shift()()}};window.Player=x;x.Moogaloop=MingClass.extend({init:function(a,b,d){function e(k,F,I){R.info("url: ",k);
var W={server:l.request.vimeo_url,player_server:l.request.player_url,cdn_server:l.request.cdn_url,embed_location:l.request.referrer,force_embed:b.force_embed,force_info:b.force_info,moogaloop_type:ba,js_api:1,js_getConfig:b.ref_id+".getConfig",js_setConfig:b.ref_id+".setConfig",clip_id:l.video.id,fullscreen:1},ca={id:F.id,name:F.id,styleclass:Z};if(B.ie)k+=(k.indexOf("?")>0?"&":"?")+"time="+(new Date).getTime();for(attr in I)if(I.hasOwnProperty(attr))W[attr]=I[attr];swfobject.embedSWF(k,F.id,"100%",
"100%","10.0.0","/assets/flash/expressInstall.swf",W,{allowscriptaccess:"always",allowfullscreen:"true",scalemode:"noscale",quality:"high",wmode:"opaque",bgcolor:"#000000"},ca,function(H){if(B.safari&&B.win){R.debug("Removing invisible from swfobject");$m.removeClass(H.ref,Z)}B.android&&B.android<2.2&&$m.removeClass(H.ref,Z);setTimeout(function(){if($m.hasClass(F,Wa))return k.indexOf(v)===0?E.loverLoaded():E.moogaloopLoaded();else if(y&&$m.hasClass(y,Z))return k.indexOf(v)===0?E.loverThumbLoaded(true):
E.moogaloopThumbLoaded(true)},2E3)})}function c(){setTimeout(function(){m.fire(tb)},0)}function n(){var k="cover"+d.uniqueId;N=document.getElementById(k);if(!N){N=document.createElement("div");N.setAttribute("id",k);$m.addClass(N,kd);a.appendChild(N)}e(v,N,{js_onLoad:b.ref_id+".player.loverLoaded",js_onThumbLoaded:b.ref_id+".player.loverThumbLoaded",js_setupMoog:b.ref_id+".player.loverInitiated"});l.embed.autoplay=1}function j(){var k="player"+d.uniqueId;fa=document.getElementById(k);if(!fa){fa=document.createElement("div");
fa.setAttribute("id",k);a.appendChild(fa)}e(s,fa,{js_onLoad:b.ref_id+".player.moogaloopLoaded",js_onThumbLoaded:b.ref_id+".player.moogaloopThumbLoaded"})}function h(){y&&y.api_pause()}function o(){if(X)E.loverInitiated();else y&&y.api_play()}function q(k){y&&y.api_seekTo(k.data)}function p(){y&&y.api_unload()}function g(k){l.embed.color=k.data;y&&y.api_changeColor(k.data)}function r(k){l.embed.loop=!!k.data;y&&y.api_setLoop(l.embed.loop)}function D(k){if(y){k=k.data;if(l.embed.api.version<2)k*=100;
y.api_setVolume(k)}}function t(k){var F=false;switch(k.name){case Fa:F=y?y.api_getCurrentTime().toFixed(3):0;break;case Ga:F=y?y.api_getDuration().toFixed(3):l.video.duration;break;case Va:F=y?y.api_getVolume().toFixed(3):l.user.preferences.volume/100;break;case Na:F=y?!!y.api_paused():true;break}i.sendBack(k.name,F)}function A(k){try{k.data=JSON.parse(k.data)}catch(F){}var I=l.embed.api.version<2?k.data:"on"+k.data.ucfirst();if(y){y.api_addEventListener(k.data,b.ref_id+".player."+I);R.debug("Adding listener",
k.data,b.ref_id+".player."+I)}else{R.debug("Queuing listener",k.data,b.ref_id+".player."+I);w.push(["addEventListener",k.data,b.ref_id+".player."+I])}}R.info("Options:",b);R.info("Config:",d.config);var E=this,l=d.config,B=d.ua,z=d.playerMode===jc?Mb:d.playerMode,i=d.api,m=i.events,v=b.swfs.cover[z],s=b.swfs.player[z+(FlashDetect.major>=10&&FlashDetect.minor>=2&&!B.linux?"_sv":"")],w=[],u,N,fa,X,y,ba=(z===db?"mobi":"mooga")+"loop"+(l.embed.on_site?"_local":"");E.config=l;R.info("swfUrl: ",s,"playerMode: ",
z);l.embed.api.on&&m.bind(pb,h).bind(qb,o).bind(rb,q).bind(sb,p).bind(Ua,g).bind(bb,r).bind(cb,D).bind(Fa,t).bind(Ga,t).bind(Va,t).bind(Na,t).bind(lc,A);E.onProgress=function(k){m.fire(kb,k.toFloat().toFixed(3))};E.onPlayProgress=function(k){m.fire(kb,{seconds:k.seconds.toFloat().toFixed(3),percent:k.percent.toFloat().toFixed(3),duration:k.duration.toFloat().toFixed(3)})};E.onLoading=function(k){m.fire(jb,{bytes:k.bytesLoaded.toInt(),percent:k.percent.toFloat().toFixed(3)})};E.onLoadProgress=function(k){m.fire(jb,
{percent:k.percent.toFloat().toFixed(3),bytesLoaded:k.bytesLoaded.toInt(),bytesTotal:k.bytesTotal.toInt(),duration:k.duration.toFloat().toFixed(3)})};E.onPlay=function(){m.fire(ib)};E.onPause=function(){m.fire(hb)};E.onSeek=function(k){m.fire(lb,l.embed.api.version<2?k.toFloat().toFixed(3):{seconds:k.seconds.toFloat().toFixed(3),percent:k.percent.toFloat().toFixed(3),duration:k.duration.toFloat().toFixed(3)})};E.onFinish=function(){m.fire(xb)};E.loverLoaded=function(){R.info("Lover loaded");$m.removeClass(a,
Wa);X=document.getElementById("cover"+d.uniqueId);c();setTimeout(function(){if($m.hasClass(X,Z)){R.debug("Removing invisible from loaded timeout");E.loverThumbLoaded(true)}},Oc)};E.loverThumbLoaded=function(k){R.info("Lover thumbnail loaded?",k);if(!X){X=document.getElementById("cover"+d.uniqueId);c()}$m.removeClass(X,Z);$m.addClass(u,M)};E.loverInitiated=function(){R.debug("Lover play button clicked");j()};E.moogaloopLoaded=function(){$m.removeClass(a,Wa);y=document.getElementById(b.ref_id);if(X){$m.remove(X);
$m.removeClass(y,Z);X=null}else c();if(l.embed.api.on&&w.length>0)for(;w.length>0;){var k=w.shift(),F="api_"+k.shift();R.debug("Calling",F,"from queue",k);(new Function("this."+F+'("'+k.join('","')+'")')).call(y)}R.info("Welcome to Moogaloop!");setTimeout(function(){if($m.hasClass(y,Z)){R.debug("Removing invisible from loaded timeout");E.moogaloopThumbLoaded(true)}},Oc)};E.moogaloopThumbLoaded=function(k){R.info("Moog thumbnail loaded?",k);y||(y=document.getElementById(b.ref_id));$m.removeClass(y,
Z);$m.addClass(u,M)};E.destroy=function(){l.embed.api.on&&m.unbind(pb,h).unbind(qb,o).unbind(rb,q).unbind(sb,p).unbind(Ua,g).unbind(bb,r).unbind(cb,D).unbind(Fa,t).unbind(Ga,t).unbind(Va,t)};for(u=a.getElementsByTagName("div")[0];u.nextSibling;)a.removeChild(u.nextSibling);!(l.embed.on_site||l.embed.autoplay||l.embed.api.on||B.opera||z===db||l.security.privacy==="password")?n():j();a.parentNode.api_seekTo=function(k){q({data:k})}}});
x.NoPlayer=MingClass.extend({init:function(a,b,d){function e(){var r=Math.round(a.clientWidth/2-h.clientWidth/2),D=Math.round(a.clientHeight/2-h.clientHeight/2);h.style.left=r+"px";h.style.top=D+"px"}function c(){g.get(cssPath,function(r){p=r;n()})}function n(){var r,D=document.createElement("style");r=q.substring(q.indexOf("<style>"),q.indexOf("</style>")+8);p+=r.replace(/<(\/)?style>/g,"");q.replace(r,"");if(d.ua.ie){D.type="text/css";D.styleSheet.cssText=p}else D.appendChild(document.createTextNode(p));
document.getElementsByTagName("head")[0].appendChild(D);h.innerHTML=q;if(script=h.getElementsByTagName("script")[0])setTimeout(function(){(new Function(script.innerHTML)).call(d.config)},0);setTimeout(function(){j.show()},100)}var j=this,h=a.children[3],o=a.children[4],q,p,g=new XHR;htmlPath=b.html_path+"/ming_overlay_"+d.playerType+".html";cssPath=b.css_path;j.element=a;j.show=function(){var r=h.getElementsByTagName("div")[0];$m.removeClass(h,M);$m.removeClass(o,M);e();setTimeout(function(){$m.addClass(r,
Xb);$m.addClass(a,ua)},10)};for(window.addEventListener?window.addEventListener("resize",e,false):window.attachEvent("onresize",e);h.previousSibling;){if(h.previousSibling.className===ac)break;a.removeChild(h.previousSibling)}$m.removeClass(a,Wa);(function(){g.get(htmlPath+"?"+(new Date).getTime(),function(r){q=r;c()})})()}});x.API=MingClass.extend({init:function(a){function b(l){if(!l||l==="")return false;try{return JSON.parse(l)}catch(B){var z=
{},i,m,v;l.split("&").forEach(function(s){i=s.split("=");m=decodeURIComponent(i[0]);v=decodeURIComponent(i[1]);if(m!=="id"){if(m==="params")m="value";if(v.contains(","))v=v.split(",")[0];z[m]=v}});return z}}function d(l){if($m.type(l)!=="string"){l=(l=l)||{};if(p)l.player_id=p;l.data==="undefined"&&delete l.data;if(q>1&&window.JSON)l=JSON.stringify(l);else{var B="method="+encodeURIComponent(l.method||l.event)+"&params=",z=[];if(l.value)z.push(encodeURIComponent(l.value));else if($m.type(l.data)===
"object")for(var i in l.data)z.push(encodeURIComponent(l.data[i]));else l.data&&l.data!=="undefined"&&z.push(encodeURIComponent(l.data));l.player_id&&z.push(l.player_id);l=B+z.join(",")}}window.parent.postMessage(l,h);R.debug("<- Sent",l)}function e(l){var B=l.name,z=l.data;try{z=JSON.parse(l.data)}catch(i){}if(q<2){B=$m.findKey(B,r);switch(B){case "onSeek":case "onProgress":z.percent&&delete z.percent;case "onLoading":z.duration&&delete z.duration;break}}if(o[B]===true||l.name===tb)d({event:B,data:z})}
function c(l){var B=b(l.data);l=B.method;var z=B.value;if(!B||!l)return false;if(l.substr(0,4)==="api_"){l=l.substr(4);l=A[l]||l;l=l.replace("()","")}B=l+"()";if(B===lc){o[z]=true;E.fire(lc,z);R.debug("-> Now listening for",z)}else if(B===Bc){o[z]=false;E.fire(Bc,z);R.debug("-> Stop listening for",z)}else if(D.contains(B)){R.debug("-> Received",l,z);switch(B){case cb:z=z.toFloat();if(q<2)z/=100;break;case bb:z=!!z.toInt();break;case Ua:if(z.search(/^[A-Fa-f\d]+$/g)===-1||z.length!==3&&z.length!==
6){R.warn("Invalid color value");return}break}E.fire(B,z)}else if(t.contains(B)){R.debug("-> Received request for",l,z);E.fire(B,z)}}function n(l){var B=false;switch(l.name){case Cc:B=a.embed.color;break;case Dc:B=a.video.url;break;case Ec:B=a.video.embed_code;break}j.sendBack(l.name,B)}if(!a.embed.api.on){this.events=new EventManager;return false}if(!window.postMessage||!window.parent.postMessage||window.location===window.parent.location){R.warn("Player API unavailable because this browser does not support postMessage or is not loaded in an iframe.");
a.embed.api.on=0;this.events=new EventManager;return false}var j=this,h=decodeURIComponent(a.request.referrer),o={},q=a.embed.api.version,p=a.embed.api.player_id,g=[jb,kb,ib,hb,xb,lb,tb,jd],r={onFinish:xb,onLoading:jb,onLoad:tb,onProgress:kb,onPlay:ib,onPause:hb,onSeek:lb},D=[lc,Bc,qb,pb,Ua,rb,bb,cb,sb],t=[Ga,Fa,Va,Cc,zb,Dc,Ec,$a,ab,Na],A={changeColor:Ua},E=new EventManager;j.events=E;j.sendBack=function(l,B){l=l.replace("()","");if(q<2)l="api_"+l;d({method:l,value:B})};j.sendError=function(){R.error("API error")};
j.destroy=function(){window.removeEventListener?window.removeEventListener("message",c,false):window.detachEvent("onmessage",c)};g.forEach(function(l){E.bind(l,e)});E.bind(Cc,n).bind(Dc,n).bind(Ec,n);window.addEventListener?window.addEventListener("message",c,false):window.attachEvent("onmessage",c)}});x.Stats=MingClass.extend({init:function(a,b){var d=b.playerType.ucfirst()+" "+b.playerMode.ucfirst(),e=window._gaq||[],c=null,n=b.playerType===vb?"local":"",j=(b.playerType===vb?"html5_"+b.playerMode:b.playerMode===db?"mobiloop":"moogaloop")+"_"+(a.embed.on_site?n:"embed");e.push(["pt._setAccount",a.analytics.ga_account]);this.clientLog=function(){var h=new XHR,o="//"+a.request.player_url+"/log/client",
q=["request_signature="+a.request.signature,"video="+ICanHas.video,"h264="+ICanHas.video.h264,"vp8="+ICanHas.video.vp8,"vp6="+ICanHas.video.vp6,"flash="+FlashDetect.version,"touch="+ICanHas.touch,"screen_width="+screen.width,"screen_height="+screen.height].join("&");h.post(o,q,function(){})};this.googleLog=function(h,o){o=parseInt(Number(o),10);if(isNaN(o))o=undefined;R.log("google analytics:",d,h,a.video.id,o);e.push(["pt._trackEvent",d,h,a.video.id+"",o])};this.partialPlayLog=function(h,o,q){h=
parseInt(h,10);if(h>c){var p=new XHR,g="//"+a.request.player_url+"/log/partial";o="request_signature="+a.request.signature+"&seconds="+h+"&quality="+o;R.log("vimeo stats:",h,"seconds played");q?p.post(g,o):p.post(g,o,function(){});c=h}};this.vimeoLog=function(h,o,q,p){var g=new XHR,r="//"+a.request.player_url+"/log/"+h+"/"+a.video.id,D="?embed_location="+a.request.referrer+"&request_signature="+a.request.signature;D+="&type="+j;if(o)D+="&quality="+o;if(q)D+="&percent="+q;R.log("vimeo stats:",h,o,
q);p?g.post(r,D):g.post(r,D,function(){})}}});if(!x.UI)x.UI={};x.UI.CanvasElement=MingClass.extend({init:function(a){if(!a)return false;this.element=a;this.origWidth=a.getAttribute("width");this.origHeight=a.getAttribute("height");this.width=this.origWidth*Gb;this.height=this.origHeight*Gb},draw:function(a,b,d,e,c){this.setData(a).setTranslation(b).setScale(d).setColor(e).setShadow(c);
this.refresh();return this},setData:function(a){this.data=a;return this},setTranslation:function(a){this.translation=a;return this},setScale:function(a){this.scale=a;return this},setColor:function(a){this.color=a;return this},setShadow:function(a){this.shadow=a;return this},refresh:function(){var a=this.data,b=this.shadow;try{if(!a||!this.element.getContext)return false}catch(d){return false}var e=this.scale||1,c=this.translation?$m.clone(this.translation):{x:0,y:0},n=this.color||"ffffff";this.element.attr({width:this.width,
height:this.height});e*=Gb;c.x*=Gb;c.y*=Gb;var j=this.element.getContext("2d"),h;j.clearRect(0,0,this.width,this.height);j.save();j.translate(c.x,c.y);j.scale(e,e);j.fillStyle=j.strokeStyle="#"+n;if(b){j.shadowOffsetX=j.shadowOffsetY=0;j.shadowBlur=10*Gb;j.shadowColor="rgba(0,0,0,0.5)"}e=0;for(c=a.length;e<c;e++)for(h in a[e])if(b=a[e][h])if($m.isArray(b))j[h].apply(j,b);else j[h]=b;else j[h].apply(j);j.restore();return this}});