//v19 © 2011 Tynt

Tynt=window.Tynt||[];
if(typeof Tynt.TIL=="undefined"){(function(){var Ia=function(){var i=document,l=i.body,p=i.documentElement,aa=eval("/*@cc_on!@*/false"),ba=function(a,b){for(var c="",d=0;d<b;d++)c+=a;return c},A=ba("a",50),s=(Tynt.e||"")+"ic.tynt.com",t=function(){return(new Date).getTime()},D=function(a){return a.replace(/^\s+|\s+$/g,"")},M=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=a[c]},v=function(a,b,c){a=i.createElement(a);M(b,a);M(c,a.style);return a},q,N;if(window.addEventListener){q=function(a,
b,c){a.addEventListener(b,c,false)};N=function(a,b,c){a.removeEventListener(b,c,false)}}else{q=function(a,b,c){a.attachEvent("on"+b,c)};N=function(a,b,c){a.detachEvent("on"+b,c)}}var O=function(a,b){var c=location.hostname.split("."),d=2;do{var f=c.slice(c.length-d,c.length).join(".");i.cookie=a+";path=/;domain=."+f+";"+b;d++}while(i.cookie.indexOf(a)==-1&&d<=c.length);if(i.cookie.indexOf(a)==-1)i.cookie=a+";path=/;"+b},P=function(a){i.readyState=="complete"?a():q(window,"load",function(){setTimeout(function(){if(typeof i.readyState==
"undefined"&&!aa)i.readyState="complete";a()},10)})},n=function(a,b){var c=[],d=function(f,e){var h="http://"+f.replace("id="+A,"id="+Tynt.join("~"));if(h.indexOf(s+"/b/p?")>-1&&typeof Tynt.b=="string")h+="&b="+Tynt.b;var k=new Image(1,1);if(e)k.onerror=e;k.src=h};n=function(f,e){c.push([f,e])};P(function(){n=d;for(var f=0;f<c.length;f++)n(c[f][0],c[f][1]);c=null});n(a,b)},ca=function(a){var b=[],c="",d;for(d in a)if(a.hasOwnProperty(d)){b.push(c,d,"=",a[d]);c="&"}return b.join("")},Q=function(a){for(var b=
0,c=a.length<100?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(Math.random()*3844);c=Math.abs(t()-12281184E5);return da(c,7)+da((b+a)%3844,2)},ea=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?ea(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},
da=function(a,b){var c=ea(a);return ba("0",b-c.length)+c},fa=function(a){return(a=D(a))?a.split(/\s+/i).length:0},R=D((i.title||location.hostname).toString()).replace(RegExp(location.hash,"g"),""),ga=function(){for(var a=i.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")){a=a[b].getAttribute("href");b=location.protocol+"//"+location.host+location.pathname;var c=i.getElementsByTagName("base")[0];if(c)if(c=c.getAttribute("href"))b=
c;if(!a.match(/^http/)){if(a.charAt(0)=="/"){c=b.indexOf("/",9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},E=function(a){return a.replace(/^https?:\/\//,"")},F=function(a,b){for(var c=b+"=",d=a.split(";"),f=0;f<d.length;f++){for(var e=d[f];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(c)==0)return e.substring(c.length,e.length)}return null},oa=function(){var a=F(i.cookie,"tracertraffic"),b=encodeURIComponent(E(ga())),c=
i.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:false;var d=s+"/b/p?id="+A+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+t(),f=d+(b?"&cu="+b:""),e=f+(i.referrer?"&r="+encodeURIComponent(E(i.referrer)):"");a=e+"&t="+encodeURIComponent(R);n(a,function(){n(e,function(){n(f,function(){n(d)})})})},pa=function(){var a=v("style",{type:"text/css",media:"print"}),b="#tyntPrint { background-image: url(http://"+s+"/b/h?id="+Tynt.join("~")+"&ts="+t()+")}";b=i.createTextNode(b);if(a.styleSheet)a.styleSheet.cssText=
b.nodeValue;else a.appendChild(b);i.getElementsByTagName("head")[0].appendChild(a);l.insertBefore(v("div",{id:"tyntPrint"}),l.firstChild)},S=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;a.unshift(b);a.length>3&&a.pop();return true}},qa=S(),ra=S(),sa=function(){var a,b=function(){window.removeEventListener("blur",b,false);T(a);return true};return function(c){a=c.target||c.srcElement;window.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!=
"A"){window.addEventListener("blur",b,false);setTimeout(function(){i.removeEventListener("blur",b,false)},1E4)}return true}}(),ha=function(a){T(a.target||a.srcElement,true)},G,ia=function(a){a=a.target||a.srcElement;G=a.nodeName=="IMG"?a:null},U=function(){var a=function(h){return typeof h.pageX=="number"?{x:h.pageX-(p.scrollLeft?p.scrollLeft:l.scrollLeft),y:h.pageY-(p.scrollTop?p.scrollTop:l.scrollTop)}:{x:h.clientX,y:h.clientY}},b=function(h){h=a(h);return h.x<=0||h.y<=0||h.x>=l.clientWidth||h.y>=
l.clientHeight},c=function(h){h=a(h);return h.x<=0||h.y<=0||h.x>=p.clientWidth||h.y>=p.clientHeight},d=function(h){return h.target.nodeName=="#document"},f=function(h){h=a(h);return h.x<=4||h.y<=4||h.x>=p.clientWidth-4||h.y>=p.clientHeight-4},e=function(h){e=navigator.userAgent.match("MSIE")?!i.compatMode||i.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?d:f;e(h)};return function(h){if(G&&e(h)){T(G);G=null}return true}}(),ta=function(){function a(j,m){if(o(j))n(s+"/b/o?id="+
A+(m?"&i=":"&l=")+encodeURIComponent(j)+"&ts="+t())}function b(j){var m=j.target||j.srcElement;if(j.button<2)for(;m&&m!=i;){j=m.href;if(m.nodeName=="A"&&j&&location.href.split("#")[0]!=j.split("#")[0]&&!/^javascript/i.test(j)){a(j);break}m=m.parentNode}}function c(){k&&a(k,true)}function d(j){j=j.target||j.srcElement;k=j.src||j.data||"flash";q(window,"blur",c)}function f(){k=null;N(window,"blur",c)}function e(j){q(j,"mouseover",d);q(j,"mouseout",f)}function h(){k&&a(k,true)}var k,o=S();q(document,
"mousedown",b);P(function(){for(var j=i.getElementsByTagName("iframe"),m=j.length-1;m>=0;m--){var r=j[m];if(r.src)e(r);else if(r.name)try{q(frames[r.name].document,"mousedown",b)}catch(u){}}j=i.getElementsByTagName("object");for(m=j.length-1;m>=0;m--)e(j[m])});q(window,"beforeunload",h);q(window,"unload",h)},w;if(Tynt.c)w=function(){};else{Tynt.c=true;w=function(){var a=true,b,c=function(d,f){var e={id:A,wc:fa(f),c:f,f:a?1:0,t:R};M(d,e);a=false;var h=e.trace_type;delete e.trace_type;var k=e.g;delete e.g;
for(var o=[],j=["id","wc","f","w","h","t","c"],m=0;m<j.length;m++){var r=j[m],u=e[r];u&&o.push([r,encodeURIComponent(u).replace(/\'/g,"%27")]);delete e[r]}for(var x in e)if(e.hasOwnProperty(x))(j=e[x])&&o.push([x,encodeURIComponent(j).replace(/\'/g,"%27")]);e=[];m=2048-(("http://"+s+"/a/t/x#?").length+(3+k.length)+5);r=o.length;var B=u=0,y=0,V,H,W,I,J=0;for(e[J]={g:k,tp:null};u<r&&e.length<35;){V=o[u][0];x=o[u][1];W=V.length+2;H=m-W-B;if(H>0){j=x.substring(y,y+H);I=j.slice(-2).indexOf("%");if(I>-1){j=
x.substring(y,y+H-2+I);B+=I+2}B+=j.length+W;y+=j.length;e[J][V]=j}else B=m;if(B>=m){e[++J]={g:k,p:J};B=0}if(y>=x.length){u++;y=0}}e[0].tp=e.length;n(s+"/b/t/"+h+"?"+ca(e[0]));for(k=1;k<e.length;k++)n(s+"/b/x/"+h+"?"+ca(e[k]))};/tynt=nout/.test(location.href)||ta();if(window.addEventListener){navigator.userAgent.match("Firefox/2")||l.addEventListener("copy",ha,false);window.addEventListener("mousedown",ia,false);window.addEventListener("dragleave",U,false);window.addEventListener("dragexit",U,false);
i.addEventListener("contextmenu",sa,false)}else{l.attachEvent("oncopy",ha);i.getElementsByTagName("html")[0].attachEvent("ondragleave",U);l.attachEvent("onmousedown",ia)}if(i.cookie.indexOf("tracertraffic=")!=-1)if(!i.referrer||i.referrer.indexOf(location.host)==-1)O("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");oa();P(pa);return function(d,f){if(!i.getElementById("tyntSS")){var e;if(f)e=typeof getSelection!="undefined"?getSelection().toString():i.selection.createRange().text;var h=d.src;
h&&!e&&ra(h)&&c({g:Q(h),trace_type:3,w:d.width,h:d.height},h);if(e&&D(e).length&&d.nodeName!="TEXTAREA"&&d.nodeName!="INPUT"){h=qa(e);var k={trace_type:1};if(h)b=Q(e);k.g=b;var o=Tynt.m?Tynt.m(k,e):true;h&&o&&c(k,e)}}}}}var K=function(a){a=a.charCodeAt(0);return 3584<=a&&a<=3711||11904<=a&&a<=12591||12688<=a&&a<=40959||63744<=a&&a<=64255||65072<=a&&a<=65103||131072<=a&&a<=173791||194560<=a&&a<=195103},ja=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;b>=0;b--){var c=a[b];c.parentNode.removeChild(c)}},
g,ua=(Tynt.e||"")+"id.tynt.com",va={t:3,p:6,w:7},z,X,Y,wa=["","Attribution","Attribution Share Alike","Attribution No Derivatives","Attribution Non-Commercial","Attribution Non-Commercial Share Alike","Attribution Non-Commercial No Derivatives"],xa=["","http://creativecommons.org/licenses/by/3.0","http://creativecommons.org/licenses/by-sa/3.0","http://creativecommons.org/licenses/by-nd/3.0","http://creativecommons.org/licenses/by-nc/3.0","http://creativecommons.org/licenses/by-nc-sa/3.0","http://creativecommons.org/licenses/by-nc-nd/3.0"],
ka=function(a){a=a.match(/ixzz=?([^?$#]*)/);if(!a)return null;a=a[1].match(/&([^?$]*)/);if(Tynt.k)return Tynt.k.charAt(1);if(!a||!a[1])return null;return a[1]},Z=function(a){return(a=a.match(/axzz([^?$]*)/))&&a.length==2?a[1]:null},ya=function(a){var b=ga();b=b&&g.c!==false?b:location.href;b=b.replace(/#(i|a)xzz=?(.*)$/g,"");return b+"#"+("ixzz"+a)},la=function(a){var b=new Date(t()+864E5);O("tracertraffic="+a.toString(),"expires="+b.toUTCString())},za=function(){var a=location.href.match(/ixzz=?([^?&$#]*)/);
if(a=(a&&a.length==2?a[1]:null)||Tynt.h){var b=ka(location.href);a=s+"/b/v?g="+a+(/\?trace_owner_view/.test(location.href)?"&o=y":"")+"&id="+A+(b?"&s="+b:"")+"&r="+encodeURIComponent(E(i.referrer))+"&ts="+t();n(a);return true}return false},Aa=function(a){n(s+"/b/a?g="+a+"&id="+A+"&r="+encodeURIComponent(E(i.referrer))+"&ts="+t(),function(){})},ma=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},C=false,Ba=function(a){if(C)return false;C=true;var b="";if(g.a){var c=
ya(a),d='<a style="color: #003399;" href="';b+=g.ap;if(g.st)b=b+d+c+'">'+ma(R)+"</a> ";if(g.su)b=b+d+c+'">'+ma(c)+"</a>";if(g.as.length>0)b=b+"\n<br>"+g.as+" ";if(g.cc>0)b=b+"\n<br>Under Creative Commons License: "+d+xa[g.cc]+'">'+wa[g.cc]+"</a>"}if(g.el){if(b.length>0)b+="\n<br>";b+=g.el}if(z){if(b.length>0)b+="\n<br>";b=Y?b+X+d+"http://tcr"+g.s+".tynt.com/ads/"+Y+"/"+a+'">'+z+"</a>":b+X+d+"http://tcr"+g.s+".tynt.com/ads/"+z+"/"+$+"/"+a+'">'+z+"</a>"}var f,e;f=v("div",{},{overflow:"hidden",color:"#000000",
backgroundColor:"transparent",textAlign:"left",textDecoration:"none",border:"none"});if(!i.selection||!i.selection.createRange){a=getSelection();if(a.toString())if(typeof a.setBaseAndExtent!="undefined"){var h=a.getRangeAt(0);b=v("span",{innerHTML:b});if(g.t){b.innerHTML+="<br/><br/>";f.appendChild(b);f.appendChild(h.cloneContents())}else{f.appendChild(h.cloneContents());b.innerHTML="<br/><br/>"+b.innerHTML;f.appendChild(b)}ja(f);f.style.width=0.1;f.style.height=0.1;f.style.position="absolute";f.style.top=
"-1000px";f.style.left="-1001px";f.appendChild(i.createElement("br"));b=f.innerText.length;l.insertBefore(f,l.firstChild);if(f.innerText.length!=b)f.style.overflow="";a.selectAllChildren(f);setTimeout(function(){f.parentNode.removeChild(f);getSelection().setBaseAndExtent(h.startContainer,h.startOffset,h.endContainer,h.endOffset);C=false},0)}else{e=v("div",{},{height:0,position:"absolute",top:"-1000px"});e.innerHTML="<br>";if(g.t){l.insertBefore(e,l.firstChild);f.innerHTML=b+"<br><br>"}else{l.appendChild(e);
f.innerHTML="<br>"+b+"<br>"}e.appendChild(f);b=i.createRange();b.selectNode(f);a.addRange(b);window.setTimeout(function(){e.parentNode.removeChild(e);C=false},0)}}else{var k=p.scrollLeft||l.scrollLeft,o=p.scrollTop||l.scrollTop;e=v("div",{},{overflow:"hidden",position:"absolute",left:k+20+"px",top:o+20+"px",width:"1px",height:"1px"});l.insertBefore(e,l.firstChild);var j=i.selection.createRange();f.innerHTML=g.t?b+"<br><br>"+j.htmlText:j.htmlText+"<br><br>"+b;ja(f);e.appendChild(i.createElement("br"));
e.appendChild(f);b=l.createTextRange();b.moveToElementText(f);b.select();setTimeout(function(){l.removeChild(e);if(j.text!=""){j.select();p.scrollLeft=k;l.scrollLeft=k;p.scrollTop=o;l.scrollTop=o}C=false},0)}return true},Ca=function(a,b){var c=true;if(g.a||z||g.el){var d;d=D(b);if((d=d.length>=2?K(d.charAt(0))||K(d.charAt(d.length-1))||K(d.charAt(d.length/2)):K(d))&&b.replace(/\s/g,"").length>=g.aw*2||!d&&fa(b)>=g.aw)if(g.a||z||g.el){c=Ba(a.g);if(g.a)a.trace_type=0}}return c},Da=function(a){var b=
a?864E5:-5E3;b=new Date(t()+b);i.cookie="tracerabg="+a+";path=/;expires="+b.toUTCString()},Fa=function(a){var b;a:{b=i.getElementsByTagName("script");for(var c=0;c<b.length;c++)if(/\/show_afs_search\.js/i.test(b[c].src)){b=true;break a}b=false}if(!b&&Ea(location)){Tynt.b=a||Q(location.href);location.replace(location.href+"#axzz"+Tynt.b)}},Ea=function(a){if(a.hash!="")return false;if(typeof g.ba=="boolean"&&g.ba)g.ba=["/"];else if(!g.ba)return true;for(var b,c=g.ba.length-1;c>=0;c--){b=null;var d=
g.ba[c],f=d.indexOf("/");if(f!=0){b=d.slice(0,f);d=d.slice(f)}if(!b||a.host==b)if(d.charAt(d.length-1)=="#"){if(a.pathname.indexOf(d.slice(0,-1))==0)return false}else if(a.pathname==d)return false}return true},Ga=function(a){g=Tynt.i||window.tyntVariables||{};g.s=a.s||1;g.a=!(g.a==0||a.a==0);g.cc=g.cc||a.cc||0;if(g.cc>6)g.cc=0;g.b=!!(g.b||a.b);g.aw=Math.max(g.aw||8,8);if(g.a){g.ap=(g.ap||(typeof tyntAP!="undefined"?tyntAP:null)||"Read more:")+" ";g.as=g.as||(typeof tyntAS!="undefined"?tyntAS:null)||
"";g.st=!!(g.st||a.st);g.su=!(g.su==0||a.su==0);g.sp=g.sp||a.sp;if(g.sp){Y=g.spid;X=(g.spt||decodeURIComponent(a.spt||""))+" ";z=g.sp||decodeURIComponent(a.sp||"")}}},na=function(){var a=i.title.indexOf("#ixzz");if(a>-1)i.title=i.title.substring(0,a);a=i.title.indexOf("#axzz");if(a>-1)i.title=i.title.substring(0,a)},Ha=function(){for(var a=0;a<Tynt.length;a++)if(Tynt[a]&&Tynt[a].length==22)return Tynt[a];return null},L=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+1).split("&"),
d=0;d<c.length;d++){var f=c[d].split("=");if(f[0].indexOf("amp;")==0)f[0]=f[0].substring(4);b[f[0]]=f[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=i.getElementsByTagName("script"),b=0;b<a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;return null}()),$=L.user||Ha();if(!$)throw Error("Error finding Tynt Insight userId. Please check your HTML for errors.");L.user&&Tynt.push(L.user);if(!function(){var a=/tracer=test/.test(location.href);a&&n(ua+"/script/verify/"+
$);if(a)return true;if(/tracer=no_tracing/.test(location.href))return true;if(/disableTracer=/.test(location.href)){a=location.href.match(/disableTracer=([^?$]*)/)[1];var b=new Date;b.setDate(a&&a=="on"?b.getDate()+365:b.getDate()-2);O("disableTracer=y","expires="+b.toUTCString());b=v("div",{},{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",fontSize:"32px",paddingTop:"10%",border:"1px solid gray"});b.innerHTML=
"Tynt Insight has been turned "+(a&&a=="on"?"off":"on")+" in this browser.<br>You may close this window.";l.insertBefore(b,l.firstChild);return true}if(F(i.cookie,"disableTracer"))return true;return false}()){if(aa){na();i.attachEvent("onpropertychange",na)}Ga(L);var T=w();w=va[ka(location.href)];if(za()){w||(w=/tynt.com/.test(i.referrer)?3:1);la(w)}Tynt.m=Ca;if(g.b)if(Z=Z(location.href)){if("#axzz"+F(i.cookie,"tracerabg")!=location.hash){Aa(Z);la(2)}}else{Fa(F(i.cookie,"tracerabg"));Da(Tynt.b)}}};
Tynt.TIL=function(){document.body?Ia():setTimeout(Tynt.TIL,300)}})();Tynt.TIL()};
